#pragma once

enum class GameState {
    TITLE,
    MENU,
    COMMANDES_TIR,
    COMMANDES_MEMORY,
    COMMANDES_SNAKE,
    COMMANDES_FE,
    MINIGAME1,
    MINIGAME2,
    MINIGAME3,
    MINIGAME4,
    MINIGAME5,
    MINIGAME6,
    EXIT
};